import type { Metadata } from 'next'

import { Header } from '@/components'

export const metadata: Metadata = {
  title: 'devstore',
  description: 'Generated by create next app',
}

export default function StoreLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <div>
      <Header />
      {children}
    </div>
  )
}
